name: Create and publish a package
on:
  push:
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
        registry: ghcr.io
        tag_with_sha: true
        push: true
        repository: bouk/fast-postgres
